# Generated by Django 3.2 on 2022-07-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='media',
            field=models.CharField(choices=[('Acrylics on Canvas', 'Acrylics on Canvas'), ('Acrylics on Paper', 'Acrylics on Paper'), ('Acrylics on Mixed Media', 'Acrylics on Mixed Media'), ('Ink on Paper', 'Ink on Paper'), ('Pencil on Paper', 'Pencil on Paper')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
