# Generated by Django 3.2 on 2022-09-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_art_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
