# Generated by Django 3.2 on 2022-09-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
