# Generated by Django 3.2 on 2022-07-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20220722_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.category'),
        ),
        migrations.AlterField(
            model_name='art',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.media'),
        ),
    ]
