# Generated by Django 3.2 on 2022-08-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20220722_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
