# Generated by Django 3.2 on 2022-11-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('Denmark', 'Denmark'), ('Sweden', 'Sweden')], max_length=100),
        ),
    ]
