# Generated by Django 3.2 on 2022-11-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(blank=True, default='Skane', max_length=5, null=True),
        ),
    ]
