# Generated by Django 3.2 on 2022-12-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(choices=[('Skåne', 'Skåne')], default='Skåne', max_length=5),
        ),
    ]
