# Generated by Django 3.2 on 2022-12-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('Sweden', 'Sweden')], default='Sweden', max_length=100),
        ),
    ]
